"""
Django settings for Resources project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from dotenv import load_dotenv
from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-local-development-key",
)

DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    ".onrender.com",
    "127.0.0.1",
    "localhost",
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cloudinary_storage",
    "cloudinary",
    "digital",
    "ebook",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Resources.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Resources.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
    )
}

CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
]

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "Resources" / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (Uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Storage configuration
if DEBUG:
    # Development: use local filesystem
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    # Production: use Cloudinary
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME"),
        "API_KEY": os.environ.get("CLOUDINARY_API_KEY"),
        "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET"),
    }

# Authentication
LOGIN_URL = "/Resources/login/"
LOGOUT_REDIRECT_URL = "/Resources/"

# Paystack
PAYSTACK_PUBLIC_KEY = os.getenv("PAYSTACK_PUBLIC_KEY")
PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_SECRET_KEY")


# ============================================================
# EMAIL CONFIGURATION
# ============================================================
# On Render, outbound SMTP ports (587 / 465) are blocked. This means
# django.core.mail.backends.smtp.EmailBackend will hang until the
# Gunicorn worker times out (30s) and gets SIGKILLed.
#
# We therefore use Resend (via django-anymail) in production, which
# sends email over HTTPS (port 443) and works reliably on Render.
#
# Locally, we fall back to the console backend so dev emails just
# print to the terminal — no SMTP setup needed.
# ============================================================

import os

# Render sets RENDER=true in the environment automatically.
ON_RENDER = os.environ.get("RENDER", "false").lower() == "true"

if ON_RENDER:
    # Production — use Resend HTTP API (never blocks the worker)
    EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
    ANYMAIL = {
        "RESEND_API_KEY": os.environ.get("RESEND_API_KEY", ""),
    }
    DEFAULT_FROM_EMAIL = os.environ.get(
        "DEFAULT_FROM_EMAIL",
        "Foundry <noreply@yourdomain.com>",
    )
else:
    # Local dev — print emails to console (no SMTP required)
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = os.environ.get(
        "DEFAULT_FROM_EMAIL",
        "Foundry <noreply@foundry.local>",
    )

# IMPORTANT: Site URL for building absolute links (e.g., email verification)
SITE_URL = os.environ.get("SITE_URL", "http://127.0.0.1:8000").rstrip("/")
# Password reset timeout (in seconds)
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour

# Celery settings (for development, use eager mode)
CELERY_BROKER_URL = "memory://"
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True


# Meta WhatsApp API
META_ACCESS_TOKEN = os.environ.get(
    "META_ACCESS_TOKEN",
    "EAAaPZCP84CekBSTxQ0qAHqKHrlb6idCZBcpIQAF8nZACd3OeUdvptBO3qWJsJQ6juZBZBFZBnTNZBFVRmialK10ic00qqDzI92JKerl4b1Y1glgqNxd1Uy56iVwvwba5dGCHTAs6CZCQV56PXyzmVzDpGxtYpL9yX5BgSpbFRO3XrqfYX0i3qgbvGmmYC2CZCXIrO7TvaOItyyqsxNX0Hnku2OittOZAanzToB4Sl9618IDl2oQ639GUgZA4gsQ5vmV1odmRZCssTxiYkqZBZCw4bpd9ha",
)
META_PHONE_NUMBER_ID = os.environ.get("META_PHONE_NUMBER_ID", "1336806619507103")
META_WABA_ID = os.environ.get("META_WABA_ID", "1046267215057178")
META_TEST_NUMBER = os.environ.get("META_TEST_NUMBER", "+15556754266")
META_API_VERSION = os.environ.get("META_API_VERSION", "v21.0")
META_APP_SECRET = os.environ.get("META_APP_SECRET", "")       # ⚠️ Optional, can leave empty for now


# ============================================================
# FILE UPLOAD LIMITS
# ============================================================
# Force file uploads to spill to disk rather than buffering in RAM.
# This prevents Gunicorn OOM kills on Render's free tier (512 MB).
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024  # 1 MB — spill to disk quickly
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5 MB — hard cap on non-file POST data
FILE_UPLOAD_TEMP_DIR = "/tmp"  # Render provides /tmp with writable perms
