# Generated by Django 6.0.6 on 2026-07-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
