# Generated by Django 6.0.6 on 2026-07-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_alter_resource_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='most_downloaded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
