# Generated by Django 6.0.6 on 2026-09-10 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_alter_activitylog_action_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('google', 'Google Search'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('other', 'Other')], default='direct', max_length=20)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='digital.lead')),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
