# Generated by Django 6.0.6 on 2026-09-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0003_leadvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('google', 'Google Search'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('other', 'Other')], default='direct', max_length=20)),
                ('path', models.CharField(default='/', max_length=255)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['session_key', 'visited_at'], name='digital_pag_session_d2ad82_idx'), models.Index(fields=['source', 'visited_at'], name='digital_pag_source_90f551_idx')],
            },
        ),
    ]
