# Generated by Django 6.0.6 on 2026-09-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0004_pagevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='chapter_title',
            field=models.TextField(blank=True),
        ),
    ]
