# Generated by Django 6.0.6 on 2026-08-06 00:07

import digital.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0006_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(storage=digital.storages.CloudinaryRawStorage(), upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=digital.storages.CloudinaryMediaStorage(), upload_to='thumbnails/'),
        ),
    ]
