# Generated by Django 6.0.6 on 2026-08-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunk',
            options={'ordering': ['chunk_number']},
        ),
        migrations.AlterModelOptions(
            name='processingstage',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='chunk',
            name='chapter_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chunk',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
