# Generated by Django 6.0.6 on 2026-08-19 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_alter_chunk_options_alter_processingstage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingstage',
            name='book',
        ),
        migrations.DeleteModel(
            name='Chunk',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='ProcessingStage',
        ),
    ]
